# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# Vi mode
set -o vi

# Disable C-S C-Q halting
stty -ixon

# User specific aliases and functions
alias ll='ls -l'
alias myip='dig +short myip.opendns.com @resolver1.opendns.com'
