# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# Vi mode
set -o vi

# Disable C-S C-Q halting
stty -ixon

# Aliases
alias ls='ls --color=auto'
alias ll='ls -la'
alias myip='dig +short myip.opendns.com @resolver1.opendns.com'

# History size
export HISTSIZE=10000
export HISTFILESIZE=10000
export GREP_OPTIONS='--color=auto'
