" Remove menu bar, toolbar, and scroll bars
set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=L

" Font
set guifont=Consolas:h12

set sessionoptions+=resize,winpos

" Disable screen flashing
" GUI resets these on load; gvimrc is run after GUI load
set vb t_vb=
