" vim-plug plugin manager
call plug#begin('~/.vim/plugged')
Plug 'altercation/vim-colors-solarized'
Plug 'scrooloose/nerdtree'
call plug#end()

" Syntax highlighting; don't clobber existing highlighting
if !exists("g:syntax_on")
    syntax enable
endif

" Color scheme
set background=dark
silent! colo desert
silent! colo solarized

" Tab width; backspace properly removes a tab
set tabstop=4
set shiftwidth=4
set softtabstop=4

" Tab key inserts spaces
set expandtab

set smarttab
set autoindent
set smartindent

" Don't write backup files
set nobackup
set nowritebackup
set noswapfile

" Make backspace behave normally
set backspace=indent,eol,start

" Horizontal movement wraps when at the start or end of a line
set whichwrap+=<,>,h,l

" Show line numbers
set number

" Display extra whitespace
set list listchars=tab:»·,trail:·,nbsp:·

" Make it obvious where 80 characters is
set textwidth=80
set colorcolumn=+1

" Get off my lawn
nnoremap <Left> :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up> :echoe "Use k"<CR>
nnoremap <Down> :echoe "Use j"<CR>

" Key sequence timeouts
set timeoutlen=100
set ttimeoutlen=0

" Open new split panes to right and bottom, which feels more natural
set splitbelow
set splitright

" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Highlight search results
set hlsearch

" Search as characters are entered
set incsearch

" Ignore case when searching
set ignorecase

" Set to auto read when a file is changed from the outside
set autoread

" Visual autocomplete for command menu
set wildmenu

" Lines from screen edge when vertical scrolling starts
set so=5

" Open NERDTree
map <C-n> :NERDTreeToggle<CR>
