autoload -Uz compinit promptinit
compinit
promptinit

setopt AUTO_CD
setopt VI
setopt NO_BEEP
setopt EXTENDED_GLOB

# History
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt EXTENDED_HISTORY

unsetopt FLOW_CONTROL  # Disable ctrl-S/Q tty halting

alias ls='ls --color=auto'
alias ll='ls -lah'
alias vi='vim'
alias df='df -Th'
alias mkdir='mkdir -p'
alias myip='dig +short myip.opendns.com @resolver1.opendns.com'

# History search
bindkey '^R' history-incremental-search-backward
bindkey '^F' history-incremental-search-forward

SAVEHIST=10000
HISTSIZE=10000
HISTFILE=~/.zsh_history

export EDITOR=vim
export GREP_OPTIONS='--color=auto'
export KEYTIMEOUT=1  # Delay when switching to normal mode in shell
