autoload -Uz compinit promptinit
compinit
promptinit

setopt AUTO_CD
setopt VI
setopt NO_BEEP
setopt EXTENDED_GLOB

# History
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt EXTENDED_HISTORY

unsetopt FLOW_CONTROL  # Disable ctrl-S/Q tty halting

alias ls="ls -h --color='auto'"
alias ll='ls -l'

SAVEHIST=10000
HISTSIZE=10000

export EDITOR=vim
